### ISSUE TITLE
Swipe from left edge to go back on iOS

### ISSUE THREAD

**Issue by BionicBison05** [amugofjava/anytime_podcast_player#115] opened 2024-02-16 17:05 UTC
**Is your feature request related to a problem? Please describe.**
Most native apps on iOS feature the ability to swipe from the left edge to go back, so it's jarring to not be able to do that here, especially considering how high up the back button itself can be on larger screens (which isn't any different in other apps but is mitigated by swipe to go back).

**Describe the solution you'd like**
Add ability to swipe to go back, ideally as a 1-to-1 gesture (page moves with your finger rather than simply triggering a full "back" action upon any amount of swipe).

**Describe alternatives you've considered**
Nothing I can think of would really replace this as it's equal parts ergonomics and the specific swipe implementation itself to match other iOS apps.

**Additional context**
What I mean by 1-to-1:
https://github.com/amugofjava/anytime_podcast_player/assets/93722725/35eed8ef-5983-4db5-9f7f-54b62dfb909c

**Comment by amugofjava** [comment] 2024-02-18 11:05
Hi @BionicBison05,

Thanks for bringing this to my attention. I've found that the search screen is not following the swipe back gesture so I will fix that, but the remaining screens look OK. Which version of iOS are you running, and can you let me know which screens are not working correctly for you?

I've taken a recording of Anytime using the swipe back gesture:

https://github.com/amugofjava/anytime_podcast_player/assets/5526902/bce42490-6eed-4ac4-b007-588f9b35c444

**Comment by BionicBison05** [comment] 2024-02-18 16:51
It's most of them for me, which is why I just assumed it hadn't really been implemented 😅

I'm on iOS 17.3.1, here's a short screen recording showing what works and what doesn't:

https://github.com/amugofjava/anytime_podcast_player/assets/93722725/c7faff8e-fd20-43b3-b9c3-910ada798d18

**Comment by amugofjava** [comment] 2024-02-18 19:13
Thanks for the video. I'll take another look at iOS 17. 

What version of Anytime are you running?

**Comment by BionicBison05** [comment] 2024-02-18 20:35
I'm running version 1.3.5.

**Comment by Chralu** [comment] 2024-02-25 15:32
Hi,

I cannot reproduce that behavior with Anytime v1.3.7 b115 on the following devices :
 - real iPhone8, iOS 16.7.4
 - simulator iPhoneSE, iOS 17.2
 
 according to my tests, the only screen which doesn't support the iOS back gesture is the `NowPlaying` bottomsheet.

**Comment by amugofjava** [comment] 2024-02-25 17:13
Thank you very much @Chralu for investigating this.

@BionicBison05 v1.3.7 is currently in Beta and will be rolled out soon. If you would like to try it now via TestFlight, please drop me an email at support@anytimeplayer.app and I'll send you the necessary link. Thanks.

**Comment by Chralu** [comment] 2024-02-25 18:20
After more tests, routes using custom transitions (`Search` page for instance) encounter the same issue.

As explained [here](https://github.com/flutter/flutter/issues/57202#issuecomment-635002477), it is because the iOS swipe back gesture is created by `MaterialPageRoute.buildTransitions`, which we override in `SlideRightRoute`.

Maybe we could use the default Transition when `TargetPlatform` is not `Android`...

**Comment by amugofjava** [comment] 2024-02-26 20:27
Thanks for testing that @BionicBison05

**Comment by amugofjava** [comment] 2024-06-22 15:53
Closing this issue as this has now been pushed to production.

**Closed by amugofjava** 2024-06-22 15:53 UTC
Labels: testing
